### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by nautilus1905** [piyueh/totero#1]
Hi, I followed carefully the instructions to build the environment, but launching the executable

python3 /home/library/opt/totero/totero.py /home/library/Zotero

returns me:
Traceback (most recent call last):
  File "/home/library/opt/totero/totero.py", line 13, in <module>
    main()
  File "/home/library/opt/totero/totero/main.py", line 48, in main
    DocumentList(database.get_all_docs(), columns, weights),
AttributeError: 'Database' object has no attribute 'get_all_docs'

Zotero 5.0.94, Debian 10

Any hints?

**Comment by piyueh** [comment]
Hi, thanks for reporting this issue. I just fixed it in the commit 607a7b6b93b66a87b276a646b5c0e9246105081e. Could you test it again? Thanks!

**Comment by nautilus1905** [comment]
Hi,
thank you for the reply
After applying the patch I get:

$ python3 /home/library/opt/totero/totero.py /home/library/Zotero
Traceback (most recent call last):
  File "/home/library/opt/totero/totero.py", line 13, in <module>
    main()
  File "/home/library/opt/totero/totero/main.py", line 48, in main
    DocumentList(database.get_docs(), columns, weights),
  File "/home/library/opt/totero/totero/documentlist.py", line 116, in __init__
    self.reset_data(data)
  File "/home/library/opt/totero/totero/documentlist.py", line 172, in reset_data
    self._data["widget"] = self._data.apply(lambda x: _DocumentItem(x, _c, _w, _wrap), 1)
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 6014, in apply
    return op.get_result()
  File "/usr/lib/python3/dist-packages/pandas/core/apply.py", line 142, in get_result
    return self.apply_standard()
  File "/usr/lib/python3/dist-packages/pandas/core/apply.py", line 248, in apply_standard
    self.apply_series_generator()
  File "/usr/lib/python3/dist-packages/pandas/core/apply.py", line 277, in apply_series_generator
    results[i] = self.f(v)
  File "/home/library/opt/totero/totero/documentlist.py", line 172, in <lambda>
    self._data["widget"] = self._data.apply(lambda x: _DocumentItem(x, _c, _w, _wrap), 1)
  File "/home/library/opt/totero/totero/document.py", line 130, in __init__
    self.reset_columns(columns, weights)
  File "/home/library/opt/totero/totero/document.py", line 164, in reset_columns
    self._columns = self._data.index.to_list()

Thanks

**Comment by nautilus1905** [comment]
Sorry, I did a mistake closing the issue yesterday. See the log cited above in my post dated 2021/01/09.

**Comment by piyueh** [comment]
Hi, is this the complete error message? I didn't see the underlying cause of the error. Usually it's at the last line of the traceback.

**Comment by nautilus1905** [comment]
Hi, this is the complete log: 

$ python3 /home/library/opt/totero/totero.py /home/library/Zotero
Traceback (most recent call last):
  File "/home/library/opt/totero/totero.py", line 13, in <module>
    main()
  File "/home/library/opt/totero/totero/main.py", line 48, in main
    DocumentList(database.get_docs(), columns, weights),
  File "/home/library/opt/totero/totero/documentlist.py", line 116, in __init__
    self.reset_data(data)
  File "/home/library/opt/totero/totero/documentlist.py", line 172, in reset_data
    self._data["widget"] = self._data.apply(lambda x: _DocumentItem(x, _c, _w, _wrap), 1)
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 6014, in apply
    return op.get_result()
  File "/usr/lib/python3/dist-packages/pandas/core/apply.py", line 142, in get_result
    return self.apply_standard()
  File "/usr/lib/python3/dist-packages/pandas/core/apply.py", line 248, in apply_standard
    self.apply_series_generator()
  File "/usr/lib/python3/dist-packages/pandas/core/apply.py", line 277, in apply_series_generator
    results[i] = self.f(v)
  File "/home/library/opt/totero/totero/documentlist.py", line 172, in <lambda>
    self._data["widget"] = self._data.apply(lambda x: _DocumentItem(x, _c, _w, _wrap), 1)
  File "/home/library/opt/totero/totero/document.py", line 130, in __init__
    self.reset_columns(columns, weights)
  File "/home/library/opt/totero/totero/document.py", line 164, in reset_columns
    self._columns = self._data.index.to_list()
AttributeError: ("'Index' object has no attribute 'to_list'", 'occurred at index 2')

**Comment by piyueh** [comment]
From the error message, I guess it may be due to the version of Pandas. What version of Pandas were you using? When I wrote this app, I used Pandas v1.1.3.

Pandas added th method `to_list` for `Index` objects since version v0.24.0 (the version released on January 25th, 2019).

**Comment by nautilus1905** [comment]
You are right.
Updated to pandas 1.2.0.
Now it works!
Thank you very much!
